apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:wE4S9PUj7JS9cSLi7O2F3YH49HwRuT+iEjgImppYopAC6l9tc7LtH433objgwlNowJ5RTdnVEeaLdHCwMPvNSPq1HiYtAB9cEyGKMJajWfm+xyRnwNL4HjQZIPUKEcT1QvDxSho9CEv8rYMfajkXccBW7XmlAZPGdw==,iv:Kxk7MD6OzUP7nXHFUlMNAShiuFeQTqSzIqD9XBsy3+4=,tag:I8qF1PSo7griFz9D4gTAMw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp49mcc5hx6qwygh4ee5qkjh2v6hmlhr7my3lg0sy6nadnurec7q2x9dpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOHRyYzliVUp0Y2tFWU04
            blFROUR2VkJleFRnalEzMEhYdmJ6QkZUZG5nCmllSlV6bG80N2JoNzNSTXNIajMw
            YTgvZzRyTmFvdGZHY213SThOTHl2UkUKLS0tIHNOZzRvaVFsUHlEVnp6REZsZE1J
            K3NMSkdNTy9GNEZGcWsvR2puTzdURDAKXLqgnZm1XewSuMJHNAHV8ZcC+rZPKOQG
            /Aeobw9554P7BBEDx841utY4tJ3gTLgES3JLSPneTIkONOF6l+duow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T13:45:05Z"
    mac: ENC[AES256_GCM,data:o5QgOmy2RcsSH5UbWE0RTLCBXh0xzwBc5qAnL/h3UOgFXi+zGX+RvAVgze4F+Lsc5voVBxbDfEY4Nr74Uc4ZcuDp0lINIidSpeIbgqaXzgiC1dOhrGGsT6EgweDinUFQP4F7r4TEgSgcVfD9dwIM0xv9NDaQ8KB6jgPe635DawQ=,iv:BqRejd4WGQph8omxN+qjWNGQTg8fWUa63SYxCO1np68=,tag:4phQaEcb4kaaI4O3cf2Nig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
