apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ELw3sSNMfBj0HKv2Y14X4PVN2cmJNg1Y8bU1OWBCRo2WEGXmUGwZvlDB7Mgl3Ctbwq6WYRvIK2D3rdjX+ICJ069HHiZz6DJtXX1v7QYvrnetVcpEZdmA43C+hTRihh6hY1ebX+/8awez3/7XZo55s+4QF5jiclQpAPByj+vJhL6Np6Y7YY9o9D9n7vuLPo+3sXBp6FUPE0fFZV/sL3zlxX5Cy/GI7QTTgD2BdQXLRUlVtoCIXyifzUIRTtIkr/j6WcM/K9lPH1ZgLq7Y1a4HrnxzIcgeIJa0L5KjtVZtMI5AOOsGqzazkX6cmzkpcK3hqk3Ne9N4fNizGsoKjAx/aqv8I5uqSJBeEsX8bvBfbo16csFc5orELDcEAd/Ns1zq,iv:hblxWnWfHyaufrz45sN8MgPB8r/KzEEvJE/DuUd4QU8=,tag:JroLeiwcZLvQWenYpbem3g==,type:str]
    identity.pub: ENC[AES256_GCM,data:/C/ZDFrvMOxwSTL1g9Qio4EHg49/lgUlxOWR0UlLJaF6/tcwy8GovgiMgdxjeg2kuZ4OviKHl1Bron6gTkkqB0XS2P5u1X3OXRYNvMpsJ/NXv72vTptb30ed2wxqqjw8p60tt3YQWLB5WkWXfuNSW45YUQSfkkpE6OXrIZN/Zr032zlIi7vcar0VSQ6SedHu0Mr9t8vKhfwzsByErYTQD32rWTvAfzjA8mZ8I+YXk+gTAkZrKb8RF5vMNPJYweTv7kZ634oWBFJqYZZUiQ==,iv:lBttWMnkC4BeMWjLSybolC00DhvzzwJic7BSFRetIzs=,tag:JSalvLN+VEUK1DsunkteAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:zb2xTGx5AWwLwT39ou9b93pNpMk7MG2vZ3pMulUzMnJoz0+wD3+yIbkA86vpXp0AzUFzWmH4zI2MOP6LoHlGxnTioBU79z7M9be4/hfMWEEqbyC6fd+o659ckftiEw7u0MlrhL6McgxE7fIHtHH/B7S0q3D/Mdzb385ppa31RCRm9HQtXfQ9+FygiP49pJlKPrW2j5WCpr7FzuFCSzbGDJIuZkLCAyQf51d5,iv:ghHuZSKcGCDB8YM5Vjl5A1K02O1RdhNIaxlwUN487Rs=,tag:AmhBOGCWHi2SYW5ID7ecmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp49mcc5hx6qwygh4ee5qkjh2v6hmlhr7my3lg0sy6nadnurec7q2x9dpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVmJ0N2JheUN1TmY4VDZC
            RHlxRkF2Y1VkSHRRU2l5V2ZyREU5aWhvWXh3Cnc1Ym0vbHdpdllWM2p2TEkrTXdC
            dURwWUVoNjN0YVpkSkovendHdU1EL28KLS0tIEQyaC9QRVljdlpuOXRqVUVNdWRx
            d3ZMQkZIMmFNaTFJTzl2dUJUeHJjTTAKBoeuToFnwQVbKs9N/G3ZRJgFaYO0vx4G
            2ESenS3RnScm3YHgBbxzb6EOaaagaPMXjRo8cNQQPjGbvuO4pEo3lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T23:08:22Z"
    mac: ENC[AES256_GCM,data:CouIuDW64Plyh7R02+WRDeJta1B5pLU5YXgk83y4CN7GtQZl5OrDXhdKG/gs8fS7HefljBhDBHgpe2pN3Sr5GC6mLZkIIGNAOSZVNC2igqFfW9FAnQUduQNibKY/1LSeO7OtJEcfNkyr5CRY0QiFPuUxLa9zyUU0nsoaQVMjpLI=,iv:nzQstkZjZ0I+RQZtM/4RtOlVqVjaoG/2VbsNgM9DWrY=,tag:8bZWKPeTxYgFSFc65MlfJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
