apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OqWM/zSpdmm7t3wh8m4jdbLGnH8iX8HQ5VKSNVFgAGTtRchlOTvuzcjjRRBeh+r1D0VAuJF1RbNAaCKBI/K1Zhzd+diCHgZR1b6mnZ8vmRiANppZW5zyQYRJENbW7bug/RB2pdYzmJyTs2m5H3IfncWe2Tsa8vTnLz2GrIKTxmNM5KLkzHY/xFXlc6bhnqMZi1/yIsyLajWYqJx7XK2P0tqJK508LgXFSFVpc997amNAOo92CgQm6UHzB2yobK64y44IWAbY3yJuQoSJ6XfRueyey0/toyK2l/Un1nO9XqLJ2OgrsCntByDJRCMw/pb5ZJ/eRsQXS+fNcnJTlnRlVChR8LG7VZzFu5lat975JwmB0ZAneTr8hU7WE/wLHrKi,iv:PiAfgqq4ybZ1E1rpaEgOh1B1wfHijE8d2nPJpBLWwzA=,tag:LvzfbvDJe/JYZZiLSS/f8g==,type:str]
    identity.pub: ENC[AES256_GCM,data:eAUc0CvhD4kf2AqvJuQeoFTMjCYa5KK6UnoWNXYDYj4YF3Lxc2DHc6V0BV5rEG+DwGcNZVII3uygNeLaVp5BVyJmi2b7Jop4BibfNexa+XF77GVLCZYnnHhx9OrXjk/ls6SzOPQMP1kWjJ1HbEjIOOTJ3TZM6NGNbtwHAAvafyEhHfsifBWgonxy9OKPS+VchK/Au1MjoPpdTJcpvufqmBR/vL/Hy6U0FjcerYBkPQQE++esluwLWwm9i1ouVTGc49DXbKSLxr8gmY4qFg==,iv:xZ5PlwOuZ3FtrgpLjatkbbkkhrIS9OovPsvKagwMhwM=,tag:gYyLZaWgLLHlUKBp8tA6ew==,type:str]
    known_hosts: ENC[AES256_GCM,data:/pvkaJ4+mCrQzecYsrgy2fxfyk1g1sA9gv3dprVgc7IZvchZ5HFV/66gdkUteCkOv4xsonQmQHY68OGQo1Dh2nm9S7Qbpmq5EOMGHy28qhM2i9QpBtlge2GiGkI8OEWkJlcKrZ74o0AY8wTb+ZpctGTH/t2kjF4viNUM0I9M1J5xM59gtPYCEohEErgyVS+zKvHlJ3UGcv8eSPztuCvrQt74q4XKduHgvI7s,iv:j/tnNfEDzEP6fy/TqIjOnEnlbn5b4RngmbMX5b7ErBE=,tag:nMWm36CVGfa3gw3NOrEWlQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp49mcc5hx6qwygh4ee5qkjh2v6hmlhr7my3lg0sy6nadnurec7q2x9dpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZGVKK1NFemplK2lpcXU3
            Vmk1SVZNZW0rd3hnV0FDVEcwdnVkNWFOUGhvCkdUNEFlblBCQ0UxR1VOR3RkL3Bt
            ckJQVFhuTHpmYVZCN1VhV204V3ZNWmMKLS0tIHNqcFRtZzRaT0FPZDZHcGtBV1Rx
            M2ZFN1M4Rk1rU2JTNEpFVSs4STRHR28KzpWChWwCcgvbDQVT99UnPnodTBATCRKO
            uJhFVcZfNRQa8H0gMjlXgR7QS6EEDI1wb6WHg+GE3DAYIvdXW28+Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T13:06:20Z"
    mac: ENC[AES256_GCM,data:7YhBQDONvIbfg7C7ZTAjouFfgvdz0Oielsa4sS9SmC6PoV1EXfpkhMAvq4gTaRclk89cvpWKlNoVY4hZT3x8qlf+Vf392ufxzZjmGyfPWGFRA1jJ2qxMDlKVXC2VjX7QhwhDsbcndlq6kxMteoe1mP1h5g62zEgjV72HW+s1dZ4=,iv:g7LTPJ3hu0mWTjjYbo5o8iVDYXwWBcfU88suBabeCSc=,tag:7hG7BhdgFyOLCul150TlUg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
