apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tvbGe/7rwinnJSdVyaEq4iBArt+jWtQW+TR08Flzr3EKtwXZYB6l3sgC1MQLThALk6ZpEgYpExQaWa5uQyR3ZlF8OPPv/aT6ADExJL6PHP4EFhUpDF20QYXrV4NfyUjpBLn49oP9kGxAyvy/VfFR7h2NfJX37jKRG08KmQseDew9ClMuTPQ/97SrxDT+Opme6jG53ZfV7qys7hE+KKu6JBNpP47zB5kairJJLuyAo5izy2+DQX/7c28Xre/1vCJEXNdAeI2gue7xP+3PlZ2EPxJgcZc/jlPMGA04rgaSWE5B1cn9umxEE/i0KanTKhkbChq5izueucSMZOvWcpeTdNwuFsJRyQKffz05MHtqVo9v6Y94jyiFuGEKTMv15E5Q,iv:1dISgCVS5i7nQCoB2GMmdCg/gb6gSXb6lZB8H0nHMDs=,tag:69yHrcqhbxPSyXoZJzWwmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Y9e8bLXUZ+fdJwC2K61f6w2FmZdbAG9o3wFk1LmWvd2VaZtWK2VziJoOJKXsEe84j7j9PcfGfD0mcVqxmS1sHaUQfqZQc2u5YLTPGwlOUU1b8h3eCgXzxwTw2TcecteggTsNvwLmxjD/Xf2TQexN5T0c438AWZRYy+e4AwJ9tiIA/fOl1k+Eq0XGL/vsBPrVScEc1mFYDf3tLygzluYZB/MA+klVVoj/mrYlO268tM7DZd8TlZkb9xR7tu8uuqJ/Wx3UtDeQMMpP9MwcTA==,iv:esGmua4JMdz8D+VXE6dqyOW9osB+Bw5+Cvhdpi/5M6Q=,tag:Kbkw4las0nJ9BGP7ALtkLQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VvY6qZ00Oxmq2Or9hYXWPgoAbxPXcjuqD3OA15GU0X0J0969JT4QpNsJBFmH7YOZUudWsTlpnS1H771IXleG6bECglxfOBodNK6yhpgp3z2w1ZdbsDJTZ+t2PBEs6DsY+dlOuU0i9QCBQB7EVxE4e53nRlbzZpdGClBq2Xgon16W946YV9RXOI4LThUeyoYuIvM3zQiuoMj4nXYQrgKttkATBG9CdH5yRzIp,iv:k+T0HV10DlJ6OgzCOMWoYtwunT8KRDYIsck0t/udijw=,tag:sdkxCisTBUU5SrTtV07vWw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp49mcc5hx6qwygh4ee5qkjh2v6hmlhr7my3lg0sy6nadnurec7q2x9dpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbHAwMjdEOWxQSEw1VTl4
            bGdzc1IvZFJMUUJISnBTTlRuaDRMVkNoekI4CkhLV1M4OFhTMis0VVZZNjRQVG16
            a3IwSUJ2L0E1TlBKNitHVm9yQ3RjMFkKLS0tIHNqbGNydUFzU2NKVzVlVjN0NzdB
            a1ZMWHdYU1R0bEczUmxaT1pldWl0Q0kKW1wbt2PMXiDfO4hpVhNQmoSuLvrzTPnM
            V6UkQwHTW/0vOmS+Y1gB5uIkZI160lKyZhwVM5pCx8JwBayypEFflw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T23:38:22Z"
    mac: ENC[AES256_GCM,data:atc4UzfvbN++DM+7lyt+5xinm1lJgYRIV1BfQSoHXcRl6jywGSqX3mOpI995INoXHJPx2MU1/FeFG+2E0mxGARoc55zZgl0U2K5iBSSrRMnkhSkV27jVyPNYYEu2vc8jRBFra4fvi3FAEKa77wfkTxeWsiyBtYit1W/g9a6G6y4=,iv:Yv3yjrYtk7Nv9peKgnGjoVtqJkS6AW9YrlrdZxXjliY=,tag:FqZ7UCpWcwyx8ETJgipPbA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
