apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NERfJ1kfYc1GcYpShUojbghLgBWKZSZ4cXUxHk6ZkQkWamHacWMJgI7S67i3yxhJN5U2DanDnHpHmKzqpV5GvgitCOA4jNnCY6cRoVFI2PQHF+UvTtYtPi2u/KDRagQT4G/3ArwnDRAEeFmGzOKHzQv+M/S3VJi7N/rF12m+PRrnNDd9RoKiDXTkGgAl2wMfJmLGMZMiu+waJ/pw1JhsKjElTfdecL809loT7ftmfGthBa3Zvdr0hXO9Q+jyoHMMMVF0spy2U6NYZwour3CKzYo13ju1bssi6yxIG3t/TXS31J8nFHcRtFihxCSW80a1xeTxSr5RvK7dj8oQnk2e/0ho9AYGtDsXcgcKVo8L6xHhGvikO16YVknSyTwUuTU5,iv:zjpYFbLVYVvZWSsENVUuVFLNc/9DCy3LEINuB9VZ93Y=,tag:NnxjmK36gPYjCkJ3J3useg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ny/PcGXQRpHDTdZ+pbIIMj5VjJUYAScCdbeuTHSGLe4m4VrpbEz8ofVebIwOHZleUyLpE/m7m0DyYqD5LI8EzLSwWIUFrukUd6rxw7tP1rFhojECgK0ngPBZOF3hfqVHuNOtXeXkDB4T+ZZvi5BYBsIMj+5vNT4jUcOc4caAZqyqM7F1svD3pdSaqeizaKVhFu9sISxb18pX4SEU2GVMAckRou1igtPrVS02zNLfXDSlM0W52epEWgL34RV5X9fhklrkW3pQEgmR3pfS/A==,iv:oizfw7m958525REzDPeUE7f06ohuF3ozfIMLFiiKkNc=,tag:jwOu5oQX4kFQma2HXVvGAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:KTrz41ASVbWAWpxzqgjV+nJtMSkRlSq4oKLE9dSLpqvvrQSp3owwuU8Pc3TMVPk6oSCEVRXmQcDxOcJquRjgd+VSnKeBkl/TzbIjcsiA/P3o+vhcdnw4tAA2h96pGw5R0TTkP14T74m5bSgggCbN4d33O1ck8NHgdZuCf8IrH61gWNqmCKwNOKegnv8bPmcLQSpxotvPuVs2pZ0R1JExHaaBkjt8sdHiL1fC,iv:KMzbnmGsNyo7XlT9gG+On6fH/MRgRE9tuPHmr5xOtK0=,tag:HwdXr8dfYqdYILYGkdmasg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp49mcc5hx6qwygh4ee5qkjh2v6hmlhr7my3lg0sy6nadnurec7q2x9dpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNGVzbG9mczNianFnQ2Q5
            VU9FRW9mNE0zM1U4V0NGWVlTM2FUUlI4UzBZCjFPcE5QNkQzWXZ0Y2pyeG1vRXM5
            R1F2UUszQUQrNlFXM256bEdTY3VGaTAKLS0tIFFXN2d5NnBseVBsYk1NMWVwUG1F
            azQ5aFlHNUlvZjBsaUJMTUNEUmNaV1UKoPUib2UYqf/MD63w/tVw2JFH364Vl5ja
            t3gI3XCt144igl2V+oGuLKJf5n7fJCAm18mGqq1r0XQUgIShKN7EpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T23:06:40Z"
    mac: ENC[AES256_GCM,data:SDrwKODs/na1sEwwFi5XJzgio7q83JP+a7WDdcyILWh9Wnuxx6I0sMHjvUQN6/PFRav1hgX0iH6P3h36g+BX6WcYekEj6IK6hmXshpyyiARefvrwSD4eL9anWh2hFVFQ0Tacy/YJc1QnsN0sUzJjKNQqikEElKgLu1NBwZPbtyU=,iv:xt7KsEbou51dXDKe8xYv7Ksdw8MRUKLm9j4vFCSv1rQ=,tag:bwqmSMtdw0TSlF28/QnDmg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
