---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 10m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 10m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
                value: 1
  values:
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${S3_URL_RESTIC}"
        bucket: "${S3_BUCKET_RESTIC}"
        accessKey: "${S3_ID_RESTIC}"
        secretKey: "${S3_KEY_RESTIC}"
        encrKey: "${S3_KEY_RESTIC}"
    service:
      glue:
        enabled: true
        type: ClusterIP
        ports:
          control:
            enabled: true
            port: 8080
            protocol: http
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: qbit.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "192.0.0.0/8"
        excludedNetworks_IPv6: []
        env:
          VPN_TYPE: "wireguard"
          VPN_SERVICE_PROVIDER: "custom"
          WIREGUARD_ENDPOINT_IP: "${WIREGUARD_ENDPOINT_IP}"
          WIREGUARD_ENDPOINT_PORT: "${WIREGUARD_ENDPOINT_PORT}"
          WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}"
          WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}"
          WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}"
          WIREGUARD_MTU: "1390"
          WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 25s
          FIREWALL_VPN_INPUT_PORTS: "{{ .Values.service.torrent.ports.torrent.port }}"
          VPN_PORT_FORWARDING_LISTENING_PORT: "{{ .Values.service.torrent.ports.torrent.port }}"
          FIREWALL_INPUT_PORTS: '{{ printf "%v,%v" .Values.service.main.ports.main.port .Values.service.glue.ports.control.port }}'
          HTTP_CONTROL_SERVER_ADDRESS: '{{ printf "0.0.0.0:%v" .Values.service.glue.ports.control.port }}'
          FIREWALL_OUTBOUND_SUBNETS: 172.16.0.0/16,172.17.0.0/16

    configmap:
      gluetun-auth-config:
        enabled: true
        data:
          config.toml: >-
            [[roles]]

            name = "qbittorrent"

            routes = ["GET /v1/vpn/status","GET /v1/publicip/ip","GET /v1/openvpn/portforwarded"]

            auth = "none"

    persistence:
      config:
        volsync:
          - name: data
            type: restic
            credentials: cloudflare
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              enabled: true
              cacheCapacity: 10Gi
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: "${MEDIA_LOCAL}"
      gluetun-auth-config:
        enabled: true
        type: configmap
        mountPath: /gluetun/auth/config.toml
        objectName: gluetun-auth-config
        readOnly: true
        subPath: config.toml
        targetSelectAll: true
