---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
                value: 1
  values:
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${S3_URL_RESTIC}"
        bucket: "${S3_BUCKET_RESTIC}"
        accessKey: "${S3_ID_RESTIC}"
        secretKey: "${S3_KEY_RESTIC}"
        encrKey: "${S3_KEY_RESTIC}"
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 10095
      torrent:
        enabled: true
        type: ClusterIP
        ports:
          torrent:
            enabled: true
            port: 61538
            protocol: tcp
          torrentudp:
            enabled: true
            port: "{{ .Values.service.torrent.ports.torrent.port }}"
            protocol: udp
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: qbit.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: data
            type: restic
            credentials: cloudflare
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              enabled: true
              cacheCapacity: 10Gi
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: "${MEDIA_LOCAL}"
