apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${S3_URL_RESTIC}"
        bucket: "${S3_BUCKET_RESTIC}"
        accessKey: "${S3_ID_RESTIC}"
        secretKey: "${S3_KEY_RESTIC}"
        encrKey: "${S3_KEY_RESTIC}"
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 10095
      torrent:
        enabled: true
        type: ClusterIP
        ports:
          torrent:
            enabled: true
            port: 61538
            protocol: tcp
          torrentudp:
            enabled: true
            port: "{{ .Values.service.torrent.ports.torrent.port }}"
            protocol: udp
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: qbit.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "192.0.0.0/8"
        excludedNetworks_IPv6: []
        env:
          VPN_TYPE: "wireguard"
          VPN_SERVICE_PROVIDER: "custom"
          VPN_ENDPOINT_IP: "${VPN_ENDPOINT_IP}"
          VPN_ENDPOINT_PORT: "${VPN_ENDPOINT_PORT}"
          WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}"
          WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}"
          WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}"
          FIREWALL_VPN_INPUT_PORTS: "{{ .Values.service.torrent.ports.torrent.port }}"
          VPN_PORT_FORWARDING_LISTENING_PORT: "{{ .Values.service.torrent.ports.torrent.port }}"
    persistence:
      config:
        volsync:
          - name: data
            type: restic
            credentials: cloudflare
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              enabled: true
              cacheCapacity: 10Gi
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: "${MEDIA_LOCAL}"
